### ISSUE TITLE
Фуго, живой там?

### ISSUE THREAD

**Issue by godande** [fugo-dev/InstagramProxyChecker#1]

**Comment by fugo-dev** [comment]
умер бесполезно

пн, 27 апр. 2020, 3:39 Artem <notifications@github.com>:

**Comment by godande** [comment]
Дай телегу свою

**Comment by fugo-dev** [comment]
Чел, того кого ты называешь фугой уже нет.
Его аккаунты у меня, я заходил в телеграмм и писал от его имени.
Мне было интересно с кем он общался.

вт, 12 мая 2020, 13:26 Tim D. Vutor <notifications@github.com>:

**Comment by godande** [comment]
А кто ты?

**Comment by fugo-dev** [comment]
Я его друг.

вт, 12 мая 2020, 13:59 Tim D. Vutor <notifications@github.com>:

**Comment by godande** [comment]
А чего он помер?

**Comment by fugo-dev** [comment]
Он выпилился после смерти своих предков

вт, 12 мая 2020, 14:04 Tim D. Vutor <notifications@github.com>:

**Comment by godande** [comment]
Дай мне телегу свою

**Comment by fugo-dev** [comment]
last_yast

вт, 12 мая 2020, 14:09 Tim D. Vutor <notifications@github.com>:

**Comment by MaxUNof** [comment]
Фуго был из тех, кто просто любил си шарп
